### ISSUE TITLE
Trouble Setting Values With Oven Range

### ISSUE THREAD

**Issue by RebbePod** [geappliances/home-assistant-adapter#14]
I have it connected to a GRF40HSV1SS

I tried setting the light as an example but it won't let me set it, it does correctly read it when states are changed.

```yaml
  switch:
    - name: Oven Light
      unique_id: ovenlight
      command_topic: "geappliances/oven/erd/0x5111/write"
      state_topic: "geappliances/oven/erd/0x5111/value"
      payload_off: "00"
      payload_on: "01"
      device:
        name: "oven"
        identifiers: "Oven Range"
        manufacturer: "GE Appliances"
```

**Comment by ryanplusplus** [comment]
Can you share the value in ERD 0x5112? This is a bitmap that specifies which oven light values are (theoretically) allowed to be written.

**Comment by ryanplusplus** [comment]
I checked with our cooking team and on that model external oven light control isn't implemented for whatever reason. I expect that we'll see that 0x5112 comes back with a 0 (indicating that none of the oven light levels are able to be requested.

I let the cooking team know that this would be nice to add in a future OTA update. I can't make any promises about prioritization, but this is on their backlog.

**Comment by RebbePod** [comment]
@ryanplusplus 0x5112 I believe was at 00


It seems to be an issue with any input I tried, for example I tried changing the oven mode and that doesn't work either, but the sensor reading is fine.

```yaml
  select:
    - name: Oven Cook Mode
      unique_id: cookmode
      command_topic: "geappliances/oven/erd/0x5100/write"
      command_template: >
        {% set map = {
        'No Mode': '00000000000000000000000000',
        'Bake': '01015e00000000000000000000',
        'Convection Bake': '1b015e00000000000000000000',
        'Convection Roast': '24015e00000000000000000000',
        'Air Fry': '9e015e00000000000000000000',
        } %}
        {{ map[value] if value in map }}
      state_topic: "geappliances/oven/erd/0x5100/value"
      value_template: >
        {% set map = {
        '00': 'No Mode',
        '01': 'Bake',
        '02': 'Convection Bake',
        '04': 'convection Roast',
        '05': 'Air Fry',
        } %}
        {{ map[value] if value in map }}
      options:
        - "No Mode"
        - "Bake"
        - "Convection Bake"
        - "Convection Roast"
        - "Air Fry"
      device:
        name: "oven"
        identifiers: "Oven Range"
        manufacturer: "GE Appliances"
```

**Comment by ryanplusplus** [comment]
Cook mode is read only. In order to start a cook, you need to use 0x5100 (upper/single oven cook request) or 0x5200 (lower oven cook request).

You can check which ERDs are R/W vs. R in https://github.com/geappliances/public-appliance-api-documentation/blob/main/appliance_api_erd_definitions.json.

**Comment by RebbePod** [comment]
I'm using 0x5100, which it shows is R/W

**Comment by ryanplusplus** [comment]
> I'm using 0x5100, which it shows is R/W

My bad, I'm still learning to read.

**Comment by ryanplusplus** [comment]
I spot-checked the bake request (01015e00000000000000000000) which translates to Bake 350 and found no obvious mistakes. Can you pull ERD 0x510A (remote enable for upper oven) to confirm that it comes back as 01 (remote enabled)?

**Comment by RebbePod** [comment]
0x510A was set to `00`
I added this to the config:
```yaml
    - name: Oven Remote Enabled
      unique_id: ovenremote
      command_topic: "geappliances/oven/erd/0x510a/write"
      state_topic: "geappliances/oven/erd/0x510a/value"
      payload_off: "00"
      payload_on: "01"
      device:
        name: "oven"
        identifiers: "Oven Range"
        manufacturer: "GE Appliances"
```
I then tried turning it on which successfully set it to `01`, but still nothing on the setting the bake options, I also realized it toggled off after pressing most buttons on the oven (like bake broil timer or clock).

I then tried turning off the oven after it was on and that mode worked whether the ERD 0x510A was on or off. 

Maybe I got the modes wrong for this model?

**Comment by ryanplusplus** [comment]
Okay, I had to do some digging, but I think I understand the problem. Your oven is not a WiFi oven and because it's never been commissioned to WiFi, it always thinks that the remote enable is disabled. Obviously this is a bit of a weird case because we didn't anticipate having the home assistant adapter.

The reason that you can't just write 0x510A to 01 is that it's smart enough to prevent you from enabling remote enable via that ERD. However, if you write a 01 to 0xF01B (the private ERD equivalent that doesn't have this protection), this will permanently (at least until you change it back) enable remote enable and this will be reflected via 0x510A. The complicated part is that the adapter doesn't let you write to the private ERDs in the 0xFxxx space.

The easiest way around this would be to use https://registry.platformio.org/libraries/geappliances/arduino-gea3 with the home assistant adapter to do a one-time write to of 01 to 0xF01B. I don't know your familiarity level with Arduino -- is this something you think you're able to do?

**Comment by RebbePod** [comment]
Thanks for finding that!

I'm not very familiar but with some help I think I can do it.

Does it makes sense to add the 0xFxxx to the main code or at least that single 0xF01B option so people with these models can take advantage? 



With some chatGPT help, does this look right?
```cpp
#include <Arduino.h>
#include <GEA3.h>

static GEA3 gea3;

void setup()
{
  Serial.begin(115200);
  Serial1.begin(GEA3::baud);
  gea3.begin(Serial1);

  if(gea3.writeERD(0xF01B, GEA3::U8(0x01)) == GEA3::WriteStatus::success) {
    Serial.println("Wrote ERD 0xF01B successfully");
  }
  else {
    Serial.println("Failed to write ERD 0xF01B");
  }
}

void loop()
{
  gea3.loop();
}
```

**Comment by ryanplusplus** [comment]
> Does it makes sense to add the 0xFxxx to the main code or at least that single 0xF01B option so people with these models can take advantage?

The way this works now is that the adapter only subscribes to MQTT topics for ERDs that it discovered on the appliance (which will only include public ERDs). I'd have to change how that works, but as long as the Arduino MQTT library supports the correct wildcard subscribes it shouldn't be too much work. It seems like it would be a nice feature to have.

> With some chatGPT help, does this look right?

Close, I think you need to update your `Serial1.begin` call to this to get the correct pins:

```c
  Serial1.begin(GEA3::baud, SERIAL_8N1, D7, D6);
```

I don't see any other obvious issues.

**Comment by RebbePod** [comment]
Ok that did it!

Now it goes on to bake mode. `Oven Remote Enabled` still shuts off after entering bake made but I can easily toggle that on every time I need to set it.

Now I gotta figure out how to control the temperature and sabbath mode :) 

There is a whole bunch of Incoming ERDs that aren't on the list, is there anyway to tell what those do?

**Comment by ryanplusplus** [comment]
These are public ERDs that aren't advertised via Appliance API. Since they aren't in Appliance API, they're omitted from the docs.

```
0x004e - Enhanced sabbath mode supported
0x007f - Git hash
0x008d - Uptime
0x008f - Related to service
0x0090 - Related to service
0x0092 - Appliance API manifest
0x0093 - Appliance API manifest
0x0094 - Appliance API manifest
0x0103 - Used for OTA
0x0104 - Used for OTA
0x0105 - Used for OTA
0x500b - Related to BLE time sync with OTR microwaves
0x500c - Related to BLE time sync with OTR microwaves
0x500d - Related to BLE time sync with OTR microwaves
0x5902 - Gas cooktop usage time
```

Nothing terribly interesting

**Comment by RebbePod** [comment]
Ok thanks.

Is it normal behavior to have to hit override each time before setting the cook mode?

If yes we can close this issue.

**Comment by RebbePod** [comment]
Another one that doesn't seem to do anything is "Control User Interface Locked" on `0x0004`

Any idea what that is supposed to do?

**Comment by RebbePod** [comment]
In mqtt explorer is shows success but it doesn't lock anything

**Comment by ryanplusplus** [comment]
I checked the firmware and I think that 0 is unlocked and 1 is locked. Can you check to see if these values work?

**Comment by RebbePod** [comment]
No luck with that either
```yaml
    - name: Control User Interface Locked
      unique_id: control_user_interface_locked
      command_topic: "geappliances/oven/erd/0x0004/write"
      state_topic: "geappliances/oven/erd/0x0004/value"
      value_template: "{{ value[:2]|string }}"
      payload_on: "01"
      payload_off: "00"
      state_on: "01"
      state_off: "00"
      device:
        name: "oven"
        identifiers: "Oven Range"
        manufacturer: "GE Appliances"
```
