### ISSUE TITLE
Enhanced Sabbath Mode Not Working?

### ISSUE THREAD

**Issue by RebbePod** [geappliances/home-assistant-adapter#17]
I set enhanced Sabbath Mode to "active" and that is supposed to make it that it doesn't recoginse the door being opened, but it seems to still detect it.

I tried it with and without having the regular sabbath mode enabled first

```yaml
  select:
    - name: Sabbath Mode
      unique_id: sabbath_mode
      command_topic: "geappliances/oven/erd/0x0009/write"
      command_template: >
        {% set map = {
        'Disable': '00',
        'Enable': '01'
        } %}
        {{ map[value] if value in map }}
      state_topic: "geappliances/oven/erd/0x0009/value"
      value_template: >
        {% set map = {
        '00': 'Disable',
        '01': 'Enable'
        } %}
        {{ map[value] if value in map else 'Not Applicable' }}
      options:
        - "Disable"
        - "Enable"
      device:
        name: "oven"
        identifiers: "Oven Range"
        manufacturer: "GE Appliances"

    - name: Enhanced Sabbath Mode
      unique_id: enhanced_sabbath_mode
      command_topic: "geappliances/oven/erd/0x004f/write"
      command_template: >
        {% set map = {
        'Inactive': '00',
        'Active': '01'
        } %}
        {{ map[value] if value in map }}
      state_topic: "geappliances/oven/erd/0x004f/value"
      value_template: >
        {% set map = {
        '00': 'Inactive',
        '01': 'Active'
        } %}
        {{ map[value] if value in map else 'Unknown' }}
      options:
        - "Inactive"
        - "Active"
      device:
        name: "oven"
        identifiers: "Oven Range"
        manufacturer: "GE Appliances"
```

**Comment by ryanplusplus** [comment]
There are a couple of additional ERDs required to make this work. You should be able to write these values to kick it into Sabbath mode with 0x004F as 01:
- 0x003D (Minutes until sunset) -> 0
- 0x003E (Minutes until next Sabbath) -> -1 (signed 2's complement number)
- 0x003F (Minutes Until Next Jewish Holiday) -> -1 (signed 2's complement number)

**Comment by ryanplusplus** [comment]
> Ok so to turn on sabbath mode I'd need to set all of them? Or is there difference between holiday mode and sabbath mode that I'd set either 0x003E or 0x003F based on that?

My understanding is you need to write all of them. I just realized that these aren't in the documentation because they aren't in any Appliance API features. I think these are the full values to write:
- 0x003D: 00000000
- 0x003E: FFFF
- 0x003F: FFFFFFFF

**Comment by ryanplusplus** [comment]
I'll be honest, I have not written any HA yaml.

@paulgoodjohn?

**Comment by paulgoodjohn** [comment]
So my knowledge of sabbath mode comes from the water heater program, not from cooking but honestly it should be mostly the same. That said....

1.  `0x003D: Minutes until sunset - Is this supposed to be the daily sunset?` Yes, actually that's exactly what it is, and the reason you need it is for when you are observing sabbath or a holiday - since the other ERDs are negative, you wouldn't know when to stop observing without this one.
2. `0x003E: Minutes until next Sabbath - I'm assuming this is until sunset of friday evening` Yep, exactly this.
3. `0x003F: Minutes until next Jewish holiday - Why is this a separate option is there a difference in what the oven does when it knows its sabbath vs a holiday?` Hooo boy :) There are different rules for keeping kosher on different appliances. As a for-instance, while a water heater may not heat at all on sabbath, it CAN heat during a holiday, just not in response to a human action. There are different rules for fridges and ranges I'm sure - I just don't know the nuances. I vaguely remember that the range operation is based on the concept of a golem - the heat is turned on based on a timer, and off by a thermostat (since you may not start a fire on the sabbath but you CAN extinguish one). Also, just for reference, holidays can and do happen on days adjacent to sabbath so it gets kind of complex handling the transitions. 

I think starting with the Hebrew calendar is a GREAT approach and I think this would make a fascinating project - please keep us updated with your progress and share it with others....

**Comment by RebbePod** [comment]
Thanks for clearing that up!

Just to make sure I understand, here is an example for a case where there is a holiday on sunday and monday. (a bit simplified because technically sabbath ends about an hour after sunset)


Friday evening 1 hour before sunset 

- `Minutes until sunset` will be 60
- `Minutes until next Sabbath` will be 60
- `Minutes until next Jewish holiday` will be 1550 (24 hours + 60 minutes)

Saturday evening 1 hour before sunset 

- `Minutes until sunset` will be 60
- `Minutes until next Sabbath` will be 8700 (24 hours x 60 x 6 days + 60 minutes)
- `Minutes until next Jewish holiday` will be 60
It knows to switch to holiday mode in 60 minutes.

Sunday evening 1 hour before sunset 

- `Minutes until sunset` will be 60
- `Minutes until next Sabbath` will be 7260 (24 hours x 60 x 5 days + 60 minutes)
- `Minutes until next Jewish holiday` will be 60
It knows to keep holiday mode on because the minutes till holiday is counting down each day individually.


Ok I think that makes sense :) 
Would love to make this work, the hebrew calendar part is easy (as in I have it set up already), the question is more about how to get this on ESPHome so I can work it from there.

**Comment by paulgoodjohn** [comment]
OK, as far as I know there are never 2 holidays back to back - and as far as the Sabbath Keeper is concerned (the box that drives this stuff) sabbath ends at sunset on the Saturday (so 1 hour before sunset on Saturday it would be -(23 * 60) (or close to that)

We ARE working on the generic ESPHome part but that's a LOT more complex than what we have right now. The actual control of the appliance is probably better done as a Home Assistant automation, since really all you have to do is drive those sabbath ERDs...

**Comment by paulgoodjohn** [comment]
Ooo, also - please when you have the yaml working for the sabbath stuff stick it up as a PR on https://github.com/geappliances/home-assistant-examples/tree/master

Thanks

**Comment by RebbePod** [comment]
Hmm... almost every holiday is two days—it's the same holiday celebrated over two days. (Fun fact: in Israel, they only celebrate one, not to confuse you even more! 🙂)

Since the Sabbath Keeper is heavily endorsed, I'm pretty sure it does not use sunset as the time to turn off Sabbath mode.

I didn’t think I’d have to explain this part, but alas, we don’t make life easy! (This is an oversimplification.) There are differing opinions on exactly when the Jewish day ends. For the Sabbath, when we can't use electronics, we take the strictest option—meaning it starts at sunset and ends a bit after dusk. (There are still different practices regarding the exact end time used today.)

It would be an issue if someone opened the fridge between sunset and dusk on Saturday evening and the light turned on.

I assumed I could set the daily sunset time to be a bit later, aligning it with daily dusk, so that would be when it shuts off. The problem arises between the Sabbath and a holiday or between two holidays—how does it know to stay on? The time till dusk would come after the start of the next holiday, causing it to shut off too early.

On another note, I usually set things to turn on Sabbath mode earlier than sunset so that I can address any issues if it doesn’t work.

**Comment by RebbePod** [comment]
Oops I misread the `Minutes until next Sabbath` and the `Minutes until next Jewish holiday` does go to the negative so the answer should be that it knows when to turn off when the negative switches to a positive number which happens once sabbath or the holiday ends.

I'm not sure what the `Minutes until sunset` would be needed for, but this makes a lot more sense.

**Comment by paulgoodjohn** [comment]
OK, I had to go back and check - and yes, two consecutive holidays AND a sabbath bracketed with holidays are indeed possible, sorry about that. If the minutes till holiday is -ve, you're in a holiday. If minutes till sabbath is -ve, it's sabbath. 

The minutes till sunset is used on the water heater to trigger reheating in the case of 2 consecutive holidays. Not completely sure why that is to be honest, that was just the way that the rabbis wanted it :)

**Comment by RebbePod** [comment]
Got it, that is cool and those numbers sound about right.

Now back to HA, I'm having trouble setting the values and it sticking. I have regular sabbath mode disabled and advanced sabbath mode active. Anything else I'm missing?

```yaml
  number:
    - name: Minutes Until Sunset
      unique_id: minutes_until_sunset
      command_topic: "geappliances/oven/erd/0x003d/write"
      state_topic: "geappliances/oven/erd/0x003d/value"
      min: 0
      max: 1440
      step: 1
      mode: box
      value_template: >
        {{ value|int(base=16) }}
      command_template: >
        {{ value|int(base=16) }}
      device:
        name: "oven"
        identifiers: "Oven Range"
        manufacturer: "GE Appliances"
    - name: Minutes Until Next Sabbath
      unique_id: minutes_until_next_sabbath
      command_topic: "geappliances/oven/erd/0x003e/write"
      state_topic: "geappliances/oven/erd/0x003e/value"
      min: -1600
      max: 10000
      step: 1
      mode: box
      value_template: >
        {{ value|int(base=16) }}
      command_template: >
        {{ value|int(base=16) }}
      device:
        name: "oven"
        identifiers: "Oven Range"
        manufacturer: "GE Appliances"
    - name: Minutes Until Next Jewish Holiday
      unique_id: minutes_until_next_jewish_holiday
      command_topic: "geappliances/oven/erd/0x003f/write"
      state_topic: "geappliances/oven/erd/0x003f/value"
      min: -4500
      max: 350000
      step: 1
      mode: box
      value_template: >
        {{ value|int(base=16) }}
      command_template: >
        {{ value|int(base=16) }}
      device:
        name: "oven"
        identifiers: "Oven Range"
        manufacturer: "GE Appliances"
```

**Comment by paulgoodjohn** [comment]
OK, so I think for all of those I would have the device class and units specified..

And - again, not any kind of yaml expert here but whenever I've done these I have connected the command_topic/command_template on adjoining lines...
Also while the READ doesn't care about the number of digits, the WRITE really does because that tells the adapter the size of the ERD write....so maybe

```
    - name: Minutes Until Next Jewish Holiday
      unique_id: minutes_until_next_jewish_holiday
      command_topic: "geappliances/oven/erd/0x003f/write"
      command_template: >
        {{ '%04x' % value|int(0) }}
      state_topic: "geappliances/oven/erd/0x003f/value"
      value_template: >
        {{ value|int(base=16) }}
      unit_of_measurement: "min"
      device_class: "duration"`
      min: -4500
      max: 350000
      step: 1
      mode: box
      device:
        name: "oven"
        identifiers: "Oven Range"
        manufacturer: "GE Appliances"
```

This is also the point where I think I would break out MQTT Explorer and see what HA is actually writing into the write section, assuming the above doesn't work....

Hope that helps, sorry - I just changed PC here and my Tailscale link is broken so I can't actually try it out to see if my yaml makes sense, so if it isn't quite syntactically correct, that's why....

**Comment by RebbePod** [comment]
Good idea to check MQTT Explorer, here is the error: (pretty good just one extra '`')

![Image](https://github.com/user-attachments/assets/337dc406-861c-4f68-8714-e1cb5213a63b)

**Comment by RebbePod** [comment]
had to make `Minutes Until Next Sabbath` 4x and the rest 8x
```yaml
  number:
    - name: Minutes Until Sunset
      unique_id: minutes_until_sunset
      command_topic: "geappliances/oven/erd/0x003d/write"
      command_template: >
        {{ '%08x' % value|int(0) }}
      state_topic: "geappliances/oven/erd/0x003d/value"
      value_template: >
        {{ value|int(base=16) }}
      unit_of_measurement: "min"
      device_class: "duration"
      min: 0
      max: 1440
      step: 1
      mode: box
      device:
        name: "oven"
        identifiers: "Oven Range"
        manufacturer: "GE Appliances"
    - name: Minutes Until Next Sabbath
      unique_id: minutes_until_next_sabbath
      command_topic: "geappliances/oven/erd/0x003e/write"
      command_template: >
        {{ '%04x' % value|int(0) }}
      state_topic: "geappliances/oven/erd/0x003e/value"
      value_template: >
        {{ value|int(base=16) }}
      unit_of_measurement: "min"
      device_class: "duration"
      min: -1600
      max: 10000
      step: 1
      mode: box
      device:
        name: "oven"
        identifiers: "Oven Range"
        manufacturer: "GE Appliances"
    - name: Minutes Until Next Jewish Holiday
      unique_id: minutes_until_next_jewish_holiday
      command_topic: "geappliances/oven/erd/0x003f/write"
      command_template: >
        {{ '%08x' % value|int(0) }}
      state_topic: "geappliances/oven/erd/0x003f/value"
      value_template: >
        {{ value|int(base=16) }}
      unit_of_measurement: "min"
      device_class: "duration"
      min: -4500
      max: 350000
      step: 1
      mode: box
      device:
        name: "oven"
        identifiers: "Oven Range"
        manufacturer: "GE Appliances"
```
