### ISSUE TITLE
Writing to erds has no effect

### ISSUE THREAD

**Issue by mguaylam** [geappliances/home-assistant-adapter#3]
I'm trying to implement controls in Home Assistant by writing on either of those erds : `0x213b` (More Dry Option Request) or `0x2137` (Timed Dry Option Request) for the GE Ultrafast Combo but I don't get the expected ff reply and nothing happens on the appliance even if I respect the prerequisites.

I'm not sure how to debug this either. Can the circuitry handle a USB supply while being powered by the appliance?

Thank you for your help.

**Comment by ryanplusplus** [comment]
Hey @mguaylam, are you able to write to other ERDs? Can you share your yaml configuration for writing to these ERDs?

On our side I think a good next step is to add a feedback topic for each ERD that tells you whether the write completed successfully and, if it failed, why.

**Comment by mguaylam** [comment]
Here's the YAML :
```YAML
mqtt:
  switch:
    - name: "Séchage supplémentaire"
      state_topic: "geappliances/ultrafast-combo/erd/0x213a/value"
      command_topic: "geappliances/ultrafast-combo/erd/0x213b/value"
      payload_on: "01"
      payload_off: "00"
      state_on: "01"
      state_off: "00"
      unique_id: "4cdcbdf6-1e15-408b-9675-409745d265ca"
      icon: mdi:tumble-dryer
      device:
        identifiers: "a92a4cf2-efe9-4561-a24e-0432bc7bcfa5"
        name: "Ultrafast Combo"
        manufacturer: "GE Appliances"
        model: "PFQ97HSPVDS"
```

I also tried 0x2048` (Damp Alert Option Request).
